export const KOSOVO_CITIES = [
  "Decan",
  "Dragash",
  "Drenas",
  "Ferizaj",
  "Fushe Kosove",
  "Gjakova",
  "Gjilan",
  "Gracanice",
  "Hani i Elezit",
  "Istog",
  "Junik",
  "Kacanik",
  "Kamenica",
  "Kline",
  "Kllokot",
  "Leposaviq",
  "Lipjan",
  "Malisheva",
  "Mamusha",
  "Mitrovica (Jugut)",
  "Mitrovica (Veriut)",
  "Novo Brdo",
  "Obiliq",
  "Partesh",
  "Peja",
  "Podujeva",
  "Prishtina",
  "Prizren",
  "Rahovec",
  "Ranillugu",
  "Skenderaj",
  "Shtime",
  "Shterpce",
  "Suhareka",
  "Viti",
  "Vushtrri",
  "Zubin Potok",
  "Zvecan",
] as const;

export type KosovoCity = (typeof KOSOVO_CITIES)[number];